// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf95ZUZLq3okgodR-QTmkom-odPQS4Opo',
    appId: '1:822427855529:web:9a996dd51c214decbf17b8',
    messagingSenderId: '822427855529',
    projectId: 'task-management-6a415',
    authDomain: 'task-management-6a415.firebaseapp.com',
    storageBucket: 'task-management-6a415.firebasestorage.app',
    measurementId: 'G-2JSCQX6ZK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGbLBCBccCpkTzY8h0f9wH-PPve03bXaI',
    appId: '1:822427855529:android:cc8a67e630106367bf17b8',
    messagingSenderId: '822427855529',
    projectId: 'task-management-6a415',
    storageBucket: 'task-management-6a415.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqxwxMJtJoMzOrUgFWVF1ORB2p5ijhbrs',
    appId: '1:822427855529:ios:f5e4b18d0b3fedc8bf17b8',
    messagingSenderId: '822427855529',
    projectId: 'task-management-6a415',
    storageBucket: 'task-management-6a415.firebasestorage.app',
    iosBundleId: 'com.example.taskManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqxwxMJtJoMzOrUgFWVF1ORB2p5ijhbrs',
    appId: '1:822427855529:ios:f5e4b18d0b3fedc8bf17b8',
    messagingSenderId: '822427855529',
    projectId: 'task-management-6a415',
    storageBucket: 'task-management-6a415.firebasestorage.app',
    iosBundleId: 'com.example.taskManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf95ZUZLq3okgodR-QTmkom-odPQS4Opo',
    appId: '1:822427855529:web:acf7e5267b57850ebf17b8',
    messagingSenderId: '822427855529',
    projectId: 'task-management-6a415',
    authDomain: 'task-management-6a415.firebaseapp.com',
    storageBucket: 'task-management-6a415.firebasestorage.app',
    measurementId: 'G-W5JR7VLFMH',
  );
}
